[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "openssl", "gcc"]

[phases.install]
cmds = [
    "python3 -m ensurepip --upgrade",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build] 
cmds = ["python3 -c 'import asyncpg; print(\"Dependencies verified\")'"]

[start]
cmd = "python3 bot.py"
