[phases.setup]
nixPkgs = ["python39", "openssl"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build] 
cmds = ["python -c 'import asyncpg; print(\"Dependencies verified\")'"]

[start]
cmd = "python bot.py"
